version: '3.8'

services:
  devcontainer:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/path-tmpl:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    environment:
      - POETRY_VENV_IN_PROJECT=false
      - POETRY_CACHE_DIR=/tmp/poetry_cache
    user: vscode
    working_dir: /workspaces/path-tmpl
